#
# Example docker compose file to be used when deploying app to
# BalenaOS.
#
version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: unless-stopped
    environment:
      - API_BASE_URL=http://backend:7777/api/
    #ports:
    #  - 3000:3000

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.rp3
    restart: unless-stopped
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_DATABASE=my_database
      - PORT=7777
      - NODE_ENV=production
      #- NODE_MIGRATIONS_RERUN=true
      #- NODE_DB_DROP=true
      # To generate a strong secret, you can run the following command in your terminal:
      # node -e "console.log(require('crypto').randomBytes(256).toString('base64'));"
      #- JWT_SECRET=secret
      - JWT_EXPERIRES_IN=1d
    # Expose port in development setup (e.g. to access Swagger UI)
    #ports:
    #  - 7777:7777
    depends_on:
      - database

  database:
    #image: postgres:16.5-alpine3.20
    image: postgres:16-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_database
    restart: unless-stopped
    #ports:
    #  - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  rproxy:
    build:
      context: .
      dockerfile: ./apps/reverse-proxy/Dockerfile.rp3
    restart: unless-stopped
    ports:
      - 80:80
      #- 443:443
    depends_on:
      - frontend
      - backend

# e.g. location of db_volume on device:
# /mnt/data/docker/volumes/2210849_db_volume/_data/
volumes:
  db_volume:
    name: db_volume
