version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: unless-stopped
    environment:
      - API_BASE_URL=http://backend:7777/api/
    #ports:
    #  - 3000:3000

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.rp3
    restart: unless-stopped
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_DATABASE=my_database
      - PORT=7777
      - NODE_ENV=development
      #- NODE_MIGRATIONS_RERUN=true
      #- NODE_DB_DROP=true
      # To generate a strong secret, you can run the following command in your terminal:
      # node -e "console.log(require('crypto').randomBytes(256).toString('base64'));"
      #- JWT_SECRET=secret
      - JWT_EXPERIRES_IN=1d
    # Expose port in development setup (e.g. to access Swagger UI)
    #ports:
    #  - 7777:7777
    depends_on:
      - database

  database:
    image: postgres:16.5-alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_database
    restart: unless-stopped
    #ports:
    #  - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  rproxy:
    build:
      context: .
      dockerfile: ./apps/reverse-proxy/Dockerfile.rp3
    #image: rproxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend

  pihole:
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp' # Only required if you are using Pi-hole as your DHCP server
      - '8080:80/tcp'
    environment:
      TZ: 'Europe/Vienna'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      # - run the following to get the password:
      # sudo docker logs pihole | grep random
      # - Needed to access http://pi.hole/admin
    # Volumes store your data between container upgrades
    volumes:
      - 'pi_hole_volume:/etc/pihole'
      - 'pi_hole_dnsmasq_volume:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

# e.g. location of db_volume on device:
# /mnt/data/docker/volumes/2210849_db_volume/_data/
volumes:
  db_volume:
    name: db_volume
  # just as test, so it can be populated with data,
  # in the next step add the pihole service
  pi_hole_volume:
    name: pi_hole_volume
  pi_hole_dnsmasq_volume:
    name: pi_hole_dnsmasq_volume
