#
# Production docker compose file.
# Expose service via nginx on ports 443 (https) and 80 (http).
# Http traffic is forwarded to https.
#
services:
  frontend:
    container_name: frontend
    build:
      context: .
      #dockerfile: ./apps/frontend/Dockerfile
      dockerfile: ./apps/web/Dockerfile
    restart: unless-stopped
    environment:
      - API_BASE_URL=http://backend:7777/api/
      - NEXT_PUBLIC_API_BASE_URI=http://backend:7777/api/
    #ports:
    #  - 3000:3000

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: unless-stopped
    env_file:
      - config/backend_dev.env
    # Expose port in development setup (e.g. to access Swagger UI)
    #ports:
    #  - 7777:7777
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:16.5-alpine3.20
    env_file:
      - config/db_dev.env
    restart: unless-stopped
    #ports:
    #  - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  rproxy:
    container_name: rproxy
    build:
      context: .
      dockerfile: ./apps/reverse-proxy/Dockerfile
    restart: unless-stopped
    volumes:
      - ./apps/reverse-proxy/ssl/private-dev:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend

volumes:
  db_volume:
    name: db_volume
